# Generated by Django 5.0.14 on 2026-02-23 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('privacy_consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorporateInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(blank=True, max_length=120)),
                ('monthly_travelers', models.PositiveIntegerField(blank=True, null=True)),
                ('service_needs', models.CharField(choices=[('Managed Corporate Travel', 'Managed Corporate Travel'), ('Executive & VIP Travel', 'Executive & VIP Travel'), ('Conference & Event Travel', 'Conference & Event Travel'), ('Group & Project Travel', 'Group & Project Travel'), ('Travel Policy & Cost Optimization', 'Travel Policy & Cost Optimization'), ('Other', 'Other')], max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MICEInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=100)),
                ('attendees', models.PositiveIntegerField()),
                ('event_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NGOTravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('organization_type', models.CharField(max_length=100)),
                ('travel_purpose', models.TextField()),
                ('number_of_travelers', models.PositiveIntegerField()),
                ('travel_details', models.TextField()),
                ('sustainability_requirements', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTravelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('program_stage', models.CharField(max_length=100)),
                ('number_of_students', models.PositiveIntegerField()),
                ('travel_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageQuoteInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_title', models.CharField(max_length=200)),
                ('package_slug', models.CharField(blank=True, default='', max_length=220)),
                ('package_location', models.CharField(blank=True, default='', max_length=150)),
                ('package_duration', models.CharField(blank=True, default='', max_length=100)),
                ('package_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('number_of_travelers', models.PositiveIntegerField(default=1)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, default='', max_length=120)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_inquiries', to='adminside.package')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
