# Generated by Django 5.0.14 on 2026-02-23 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=40)),
                ('landing_path', models.CharField(blank=True, default='', max_length=255)),
                ('query_string', models.TextField(blank=True, default='')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('session_key', models.CharField(blank=True, default='', max_length=40)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_model', models.CharField(blank=True, default='', max_length=80)),
                ('converted_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralConsultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('landing_path', models.CharField(default='/', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='corporateinquiry',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='packagequoteinquiry',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='referral_click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to='users.referralclick'),
        ),
        migrations.AddField(
            model_name='corporateinquiry',
            name='referral_click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_inquiries', to='users.referralclick'),
        ),
        migrations.AddField(
            model_name='packagequoteinquiry',
            name='referral_click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_quote_inquiries', to='users.referralclick'),
        ),
        migrations.AddField(
            model_name='referralclick',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='users.referralconsultant'),
        ),
        migrations.AddField(
            model_name='contactinquiry',
            name='referral_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_inquiries', to='users.referralconsultant'),
        ),
        migrations.AddField(
            model_name='corporateinquiry',
            name='referral_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corporate_inquiries', to='users.referralconsultant'),
        ),
        migrations.AddField(
            model_name='packagequoteinquiry',
            name='referral_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_quote_inquiries', to='users.referralconsultant'),
        ),
    ]
