# Generated by Django 5.0.14 on 2026-02-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_referralclick_referralconsultant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporateinquiry',
            name='referral_click',
        ),
        migrations.RemoveField(
            model_name='packagequoteinquiry',
            name='referral_click',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='referral_click',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='referral_consultant',
        ),
        migrations.RemoveField(
            model_name='packagequoteinquiry',
            name='referral_consultant',
        ),
        migrations.RemoveField(
            model_name='corporateinquiry',
            name='referral_consultant',
        ),
        migrations.RemoveField(
            model_name='contactinquiry',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='corporateinquiry',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='packagequoteinquiry',
            name='referral_code',
        ),
        migrations.DeleteModel(
            name='ReferralClick',
        ),
        migrations.DeleteModel(
            name='ReferralConsultant',
        ),
    ]
