# Generated by Django 5.0.14 on 2026-03-09 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0007_careerjob'),
        ('users', '0003_remove_corporateinquiry_referral_click_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('primary_phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(blank=True, default='', max_length=20)),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('cover_letter_text', models.TextField(blank=True, default='')),
                ('cv_file_uuid', models.CharField(max_length=64)),
                ('cv_file_url', models.URLField(max_length=500)),
                ('cv_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('cv_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('cover_file_uuid', models.CharField(blank=True, default='', max_length=64)),
                ('cover_file_url', models.URLField(blank=True, default='', max_length=500)),
                ('cover_file_name', models.CharField(blank=True, default='', max_length=255)),
                ('cover_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='adminside.careerjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
