# Generated by Django 5.0.14 on 2026-03-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0009_hotel_city_hotel_country_hotel_region'),
        ('users', '0004_careerapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=220)),
                ('hotel_slug', models.CharField(blank=True, default='', max_length=220)),
                ('hotel_location', models.CharField(blank=True, default='', max_length=200)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.PositiveIntegerField(default=1)),
                ('number_of_rooms', models.PositiveIntegerField(default=1)),
                ('room_preference', models.CharField(blank=True, choices=[('single', 'Single'), ('double', 'Double'), ('twin', 'Twin'), ('family', 'Family'), ('suite', 'Suite')], default='', max_length=20)),
                ('meal_plan_preference', models.CharField(blank=True, choices=[('room_only', 'Room Only'), ('bb', 'Bed & Breakfast (BB)'), ('hb', 'Half Board (HB)'), ('fb', 'Full Board (FB)'), ('ai', 'All Inclusive (AI)')], default='', max_length=20)),
                ('budget_range', models.CharField(blank=True, default='', max_length=120)),
                ('airport_transfer_needed', models.BooleanField(default=False)),
                ('flexible_dates', models.BooleanField(default=False)),
                ('special_requests', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='adminside.hotel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
