# Generated by Django 5.0.14 on 2026-03-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_careerapplication_is_read_contactinquiry_is_read_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, default='', max_length=220)),
                ('destination', models.CharField(blank=True, default='', max_length=220)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('can_feature_publicly', models.BooleanField(blank=True, null=True)),
                ('overall_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('likelihood_to_recommend', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('category_ratings', models.JSONField(blank=True, default=dict)),
                ('highlights_selected', models.JSONField(blank=True, default=list)),
                ('best_part', models.TextField(blank=True, default='')),
                ('improvements', models.TextField(blank=True, default='')),
                ('testimonial', models.TextField(blank=True, default='')),
                ('expectation_result', models.CharField(blank=True, choices=[('exceeded', 'Exceeded'), ('met', 'Met'), ('below', 'Below')], default='', max_length=20)),
                ('would_travel_again', models.CharField(blank=True, choices=[('yes', 'Yes'), ('maybe', 'Maybe'), ('no', 'No')], default='', max_length=10)),
                ('interested_destinations', models.TextField(blank=True, default='')),
                ('can_use_media', models.BooleanField(blank=True, null=True)),
                ('media_urls', models.JSONField(blank=True, default=list)),
                ('media_uuids', models.JSONField(blank=True, default=list)),
                ('media_names', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
