# Generated by Django 5.0.14 on 2026-02-23 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='max_group_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='min_group_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='starting_price_note',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.CreateModel(
            name='PackageAvailabilityMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Jan'), (2, 'Feb'), (3, 'Mar'), (4, 'Apr'), (5, 'May'), (6, 'Jun'), (7, 'Jul'), (8, 'Aug'), (9, 'Sep'), (10, 'Oct'), (11, 'Nov'), (12, 'Dec')])),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('sold_out', 'Sold Out')], default='available', max_length=16)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_months', to='adminside.package')),
            ],
            options={
                'ordering': ['year', 'month', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageHotelOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, default='', max_length=100)),
                ('board_basis', models.CharField(blank=True, choices=[('BB', 'BB'), ('HB', 'HB'), ('FB', 'FB'), ('AI', 'AI')], default='', max_length=2)),
                ('nights', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('price_adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_recommended', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_options', to='adminside.hotel')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_options', to='adminside.package')),
            ],
            options={
                'ordering': ['-is_recommended', 'sort_order', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='packageavailabilitymonth',
            constraint=models.UniqueConstraint(fields=('package', 'month', 'year'), name='uniq_package_month_year'),
        ),
    ]
