# Generated by Django 5.0.14 on 2026-02-23 05:09

import django.db.models.deletion
from django.db import migrations, models


def seed_destinations_and_map_packages(apps, schema_editor):
    Destination = apps.get_model("adminside", "Destination")
    Package = apps.get_model("adminside", "Package")

    destination_rows = [
        ("Kenya", "kenya"),
        ("Uganda", "uganda"),
        ("Tanzania", "tanzania"),
        ("Dubai", "dubai"),
        ("South Africa", "south-africa"),
        ("Malaysia", "malaysia"),
        ("Zanzibar", "zanzibar"),
        ("Maldives", "maldives"),
    ]

    destination_map = {}
    for index, (name, slug) in enumerate(destination_rows, start=1):
        destination, _ = Destination.objects.update_or_create(
            slug=slug,
            defaults={
                "name": name,
                "active": True,
                "sort_order": index,
            },
        )
        destination_map[slug] = destination

    keyword_map = [
        ("zanzibar", ["zanzibar"]),
        ("maldives", ["maldives", "maldiv"]),
        ("dubai", ["dubai", "uae", "emirates"]),
        ("south-africa", ["south africa", "cape town", "johannesburg", "durban", "kruger"]),
        ("malaysia", ["malaysia", "kuala lumpur", "langkawi", "penang"]),
        ("uganda", ["uganda", "kampala", "entebbe", "bwindi", "murchison"]),
        ("tanzania", ["tanzania", "serengeti", "ngorongoro", "arusha", "tarangire"]),
        ("kenya", ["kenya", "nairobi", "masai mara", "maasai mara", "amboseli", "tsavo", "diani", "nakuru", "rift"]),
    ]

    for package in Package.objects.all():
        search_blob = f"{package.title or ''} {package.location or ''}".lower()
        chosen_slug = None
        for slug, keywords in keyword_map:
            if any(keyword in search_blob for keyword in keywords):
                chosen_slug = slug
                break
        if not chosen_slug:
            chosen_slug = "kenya"
        package.destination = destination_map[chosen_slug]
        package.save(update_fields=["destination"])


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0002_package_end_date_package_max_group_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='adminside.destination'),
        ),
        migrations.RunPython(seed_destinations_and_map_packages, migrations.RunPython.noop),
    ]
