# Generated by Django 5.0.14 on 2026-02-23 06:04

from django.db import migrations, models


def copy_day_inclusions_exclusions_to_package(apps, schema_editor):
    Package = apps.get_model("adminside", "Package")
    PackageItineraryDay = apps.get_model("adminside", "PackageItineraryDay")

    for package in Package.objects.all():
        if package.inclusions and package.exclusions:
            continue

        first_day = (
            PackageItineraryDay.objects.filter(package=package)
            .order_by("sort_order", "day_number", "id")
            .first()
        )
        if not first_day:
            continue

        update_fields = []
        if not package.inclusions and first_day.inclusions:
            package.inclusions = first_day.inclusions
            update_fields.append("inclusions")
        if not package.exclusions and first_day.exclusions:
            package.exclusions = first_day.exclusions
            update_fields.append("exclusions")
        if update_fields:
            package.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_destination_package_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='exclusions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='inclusions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(copy_day_inclusions_exclusions_to_package, migrations.RunPython.noop),
    ]
