# Generated by Django 5.0.14 on 2026-03-09 15:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0006_packagehoteloption_pricing_table_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('slug', models.SlugField(max_length=240, unique=True)),
                ('department', models.CharField(blank=True, default='', max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=10)),
                ('hero_image_url', models.URLField(blank=True, default='')),
                ('summary', models.TextField(blank=True, default='')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('responsibilities', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('requirements', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('posted_on', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
