# Generated by Django 5.0.14 on 2026-03-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0008_package_pricing_table_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=120),
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
