# Generated by Codex on 2026-02-23

from django.db import migrations
from shortuuid import ShortUUID


def seed_initial_news_post(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    Post = apps.get_model("blog", "Post")

    category, _ = Category.objects.get_or_create(
        slug="travel-intelligence",
        defaults={
            "title": "Travel Intelligence",
            "description": (
                "<p>Market and destination updates for organizations and travelers planning regional and international trips.</p>"
            ),
            "active": True,
        },
    )

    post = Post.objects.filter(slug="east-africa-corporate-travel-outlook-2026").first()
    if post:
        post.title = "East Africa Corporate Travel Outlook 2026: What Procurement Teams Should Track"
        post.excerpt = (
            "<p>Airfares, lead times, and policy compliance are shifting in 2026. "
            "This briefing highlights five practical actions for organizations managing high-volume travel across East Africa.</p>"
        )
        post.content = (
            "<h2>1. Book Earlier on High-Demand Regional Routes</h2>"
            "<p>Routes connecting Nairobi with major regional hubs are showing tighter booking windows. "
            "For teams with fixed travel calendars, earlier ticket confirmation reduces last-minute fare volatility.</p>"
            "<h2>2. Standardize Hotel Tiers by Trip Type</h2>"
            "<p>Define preferred accommodation tiers for field, executive, and conference travel. "
            "This improves budget control and keeps traveler comfort consistent.</p>"
            "<h2>3. Strengthen Approval Workflows</h2>"
            "<p>Organizations that align authorization forms, traveler profiles, and booking instructions are seeing fewer booking errors and faster issuance times.</p>"
            "<h2>4. Monitor Total Trip Cost, Not Ticket Cost Alone</h2>"
            "<p>Ground transfers, baggage, amendments, and schedule changes can materially affect total spend. "
            "Monthly reconciled reporting gives finance teams better visibility.</p>"
            "<h2>5. Build an After-Hours Response Protocol</h2>"
            "<p>Delays and disruptions often occur outside office hours. "
            "A documented escalation channel for urgent changes protects traveler productivity and duty of care.</p>"
            "<p><strong>Nina Insight:</strong> Organizations that integrate policy directly into booking operations are better positioned to balance cost, speed, and compliance through 2026.</p>"
        )
        post.category = category
        post.status = "published"
        post.featured = True
        post.trending = True
        post.save()
        return

    Post.objects.create(
        slug="east-africa-corporate-travel-outlook-2026",
        pid=ShortUUID().random(length=22),
        title="East Africa Corporate Travel Outlook 2026: What Procurement Teams Should Track",
        excerpt=(
            "<p>Airfares, lead times, and policy compliance are shifting in 2026. "
            "This briefing highlights five practical actions for organizations managing high-volume travel across East Africa.</p>"
        ),
        content=(
            "<h2>1. Book Earlier on High-Demand Regional Routes</h2>"
            "<p>Routes connecting Nairobi with major regional hubs are showing tighter booking windows. "
            "For teams with fixed travel calendars, earlier ticket confirmation reduces last-minute fare volatility.</p>"
            "<h2>2. Standardize Hotel Tiers by Trip Type</h2>"
            "<p>Define preferred accommodation tiers for field, executive, and conference travel. "
            "This improves budget control and keeps traveler comfort consistent.</p>"
            "<h2>3. Strengthen Approval Workflows</h2>"
            "<p>Organizations that align authorization forms, traveler profiles, and booking instructions are seeing fewer booking errors and faster issuance times.</p>"
            "<h2>4. Monitor Total Trip Cost, Not Ticket Cost Alone</h2>"
            "<p>Ground transfers, baggage, amendments, and schedule changes can materially affect total spend. "
            "Monthly reconciled reporting gives finance teams better visibility.</p>"
            "<h2>5. Build an After-Hours Response Protocol</h2>"
            "<p>Delays and disruptions often occur outside office hours. "
            "A documented escalation channel for urgent changes protects traveler productivity and duty of care.</p>"
            "<p><strong>Nina Insight:</strong> Organizations that integrate policy directly into booking operations are better positioned to balance cost, speed, and compliance through 2026.</p>"
        ),
        category=category,
        status="published",
        featured=True,
        trending=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_pid"),
    ]

    operations = [
        migrations.RunPython(seed_initial_news_post, migrations.RunPython.noop),
    ]
