# Generated by Codex on 2026-02-23

from django.db import migrations
from shortuuid import ShortUUID


def upsert_post(Post, slug, defaults):
    post = Post.objects.filter(slug=slug).first()
    if post:
        for key, value in defaults.items():
            setattr(post, key, value)
        post.save()
        return post
    return Post.objects.create(slug=slug, pid=ShortUUID().random(length=22), **defaults)


def seed_expanded_news_posts(apps, schema_editor):
    Category = apps.get_model("blog", "Category")
    Post = apps.get_model("blog", "Post")

    travel_intel, _ = Category.objects.get_or_create(
        slug="travel-intelligence",
        defaults={
            "title": "Travel Intelligence",
            "description": "<p>Operational updates, route trends, and destination advisories for better travel decisions.</p>",
            "active": True,
        },
    )
    corporate_briefings, _ = Category.objects.get_or_create(
        slug="corporate-briefings",
        defaults={
            "title": "Corporate Briefings",
            "description": "<p>Policy and procurement insights for organizations managing travel programs.</p>",
            "active": True,
        },
    )
    destination_updates, _ = Category.objects.get_or_create(
        slug="destination-updates",
        defaults={
            "title": "Destination Updates",
            "description": "<p>On-ground updates affecting leisure and corporate travel planning.</p>",
            "active": True,
        },
    )

    upsert_post(
        Post,
        "east-africa-corporate-travel-outlook-2026",
        {
            "title": "East Africa Corporate Travel Outlook 2026: What Procurement Teams Should Track",
            "excerpt": (
                "<p>Fare volatility, approval discipline, and route timing are shaping 2026 outcomes. "
                "Here is a practical framework organizations can apply to control cost while maintaining traveler productivity.</p>"
            ),
            "content": (
                "<h2>Market Direction in 2026</h2>"
                "<p>Corporate travel in East Africa is growing, but cost predictability depends on how early requests are converted to confirmed bookings. "
                "Teams that wait until the final week are facing higher fare variance and weaker schedule options.</p>"
                "<h2>Priority 1: Lead-Time Discipline</h2>"
                "<p>Create route-specific booking windows for high-frequency sectors. "
                "For routine meetings, fixed lead-time bands help reduce premium last-minute fares.</p>"
                "<h2>Priority 2: Policy-Embedded Booking</h2>"
                "<p>When approval limits and preferred suppliers are applied before ticketing, exceptions decrease and finance visibility improves.</p>"
                "<h2>Priority 3: Total Trip Cost Reporting</h2>"
                "<p>Track transport, amendment fees, and accommodation shifts alongside airfare. "
                "This reveals the real cost drivers and helps procurement focus on the right levers.</p>"
                "<h2>Priority 4: Duty of Care Readiness</h2>"
                "<p>Keep traveler profiles, emergency contacts, and after-hours support pathways current. "
                "Disruptions are operational events, not just itinerary changes.</p>"
                "<h2>Practical Action Plan</h2>"
                "<ul>"
                "<li>Define booking windows by route type.</li>"
                "<li>Publish an approvals matrix for all travel categories.</li>"
                "<li>Review monthly reports with finance and operations together.</li>"
                "<li>Assign a clear escalation path for after-hours travel incidents.</li>"
                "</ul>"
                "<p><strong>Nina Insight:</strong> Consistent travel governance outperforms ad-hoc cost cutting in both savings and traveler experience.</p>"
            ),
            "category": travel_intel,
            "status": "published",
            "featured": True,
            "trending": True,
        },
    )

    upsert_post(
        Post,
        "nairobi-regional-route-strategy-2026",
        {
            "title": "Nairobi Regional Route Strategy 2026: How to Plan Around Peak-Demand Windows",
            "excerpt": (
                "<p>Regional traffic from Nairobi is tightening around key business periods. "
                "This briefing outlines when to lock travel and how to protect schedules for mission-critical trips.</p>"
            ),
            "content": (
                "<h2>Why Route Strategy Matters</h2>"
                "<p>Nairobi remains a central gateway for East and Central Africa, and many regional routes now show compressed availability during conference and project cycles.</p>"
                "<h2>Peak-Demand Signals to Watch</h2>"
                "<ul>"
                "<li>Quarter-end and budget-cycle travel spikes.</li>"
                "<li>NGO and institutional meeting windows.</li>"
                "<li>School holiday overlaps that affect mixed business-leisure traffic.</li>"
                "</ul>"
                "<h2>How Travel Teams Can Respond</h2>"
                "<p>Segment trips into fixed-date and flexible-date buckets. "
                "Prioritize fixed-date requests for early issuance, and hold fallback options for flexible itineraries.</p>"
                "<h2>Recommended Booking Playbook</h2>"
                "<ul>"
                "<li>Set route-level lead times for frequent corridors.</li>"
                "<li>Pre-approve fare caps for urgent travel cases.</li>"
                "<li>Maintain alternate carrier and timing options before issuing final tickets.</li>"
                "</ul>"
                "<h2>Operational Benefit</h2>"
                "<p>Teams that apply this model reduce missed connections, improve meeting attendance reliability, and lower emergency amendment volume.</p>"
                "<p><strong>Nina Insight:</strong> Route strategy is strongest when policy, approvals, and booking operations are managed as one workflow.</p>"
            ),
            "category": corporate_briefings,
            "status": "published",
            "featured": False,
            "trending": True,
        },
    )

    upsert_post(
        Post,
        "kenya-safari-calendar-2026-planning-guide",
        {
            "title": "Kenya Safari Calendar 2026: A Practical Planning Guide by Season",
            "excerpt": (
                "<p>From migration windows to green-season value, this guide helps travelers and coordinators choose the right month for wildlife, budget, and logistics.</p>"
            ),
            "content": (
                "<h2>January-March: Dry-Season Clarity</h2>"
                "<p>Excellent road conditions and strong visibility support photography and classic game-drive itineraries.</p>"
                "<h2>April-May: Green Season Value</h2>"
                "<p>Lower demand periods can improve value for private travelers and small groups, while landscapes are lush and vibrant.</p>"
                "<h2>June-October: Prime Wildlife Window</h2>"
                "<p>Peak safari demand aligns with strong game viewing and migration interest. "
                "Advance planning is recommended for preferred lodges and guides.</p>"
                "<h2>November-December: Mixed Conditions, Good Flexibility</h2>"
                "<p>Late-year travel can combine city, coast, and safari products effectively when itineraries are paced with weather considerations.</p>"
                "<h2>How to Match Season to Trip Purpose</h2>"
                "<ul>"
                "<li>Corporate incentive groups: prioritize weather stability and logistics reliability.</li>"
                "<li>Family trips: favor balanced transit times and accommodation comfort.</li>"
                "<li>Photography-focused travel: align with visibility and habitat movement.</li>"
                "</ul>"
                "<h2>Planning Checklist</h2>"
                "<ul>"
                "<li>Confirm destination-specific health and documentation requirements.</li>"
                "<li>Lock accommodation and transfers early for peak months.</li>"
                "<li>Build one contingency option for weather and route adjustments.</li>"
                "</ul>"
                "<p><strong>Nina Insight:</strong> The best safari month depends on your objective, not just the general season label.</p>"
            ),
            "category": destination_updates,
            "status": "published",
            "featured": True,
            "trending": False,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_pid"),
    ]

    operations = [
        migrations.RunPython(seed_expanded_news_posts, migrations.RunPython.noop),
    ]
