# Generated by Django 5.0.14 on 2026-03-17 13:22

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pid',
            field=models.CharField(default=blog.models.generate_post_pid, editable=False, max_length=25, unique=True),
        ),
    ]
